#!/usr/bin/env bash

up(){
  local AMOUNT=${1:-1}
  for i in {1..$AMOUNT}
  do
    cd ..
  done
}

kp() {
  PID=$(echo $(lsof -n -i4TCP:$1) | awk 'NR==1{print $11}')
  kill -9 $PID
}

wu(){
  lsof -i tcp:$1
}

cln(){
  REPO=$1
  DESTINATION=${2:=$(basename "$1")}

  git clone $REPO $DESTINATION
  cd "$(basename "$REPO" .git)"
  v
}

mcd () {
  mkdir -p $1
  cd $1
}

ctp(){
  if [ -z "$1" ]
    then
      echo "Project name not provided"
      return 1
  fi

  mkdir $1
  cd $1
  git init

  echo "node_modules\n.DS_Store\n.env*\ndist" > .gitignore
  touch .env

  npm init --yes
  echo 'save-exact=true' > .npmrc

  NODE_VERSION=$(node -v | sed 's/^v\([^\.]*\).\([^\.]*\)\..*$/\1/')
  npm i -D rimraf typescript ts-node eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin prettier @commitlint/cli @commitlint/config-conventional husky @types/node@$NODE_VERSION @total-typescript/ts-reset jest @types/jest ts-jest
  npm i dotenv zod

  cat << _EOF_ >> eslint.config.mjs
import typescriptParser from '@typescript-eslint/parser';
import tsEslintPlugin from '@typescript-eslint/eslint-plugin';

export default [
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    ignores: ['reset.d.ts'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        project: './tsconfig.json',
        ecmaVersion: 'latest',
        sourceType: 'module'
      }
    },
    plugins: {
      '@typescript-eslint': tsEslintPlugin
    },
    rules: {
      ...tsEslintPlugin.configs['recommended-type-checked'].rules,
      'consistent-return': 'warn',
      eqeqeq: 'warn',
      'no-param-reassign': 'warn',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/explicit-function-return-type': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error'
    }
  }
];
_EOF_
  echo '{ "printWidth": 120, "tabWidth": 2, "useTabs": false, "semi": true, "singleQuote": true, "trailingComma": "none", "arrowParens": "avoid" }' > .prettierrc.json
  echo '{ "extends": ["@commitlint/config-conventional"] }' > .commitlintrc.json

  cat << _EOF_ >> jest.config.json
{
  "testEnvironment": "node",
  "roots": ["<rootDir>/dist/test"],
  "setupFiles": ["dotenv/config"]
}

_EOF_
  cat << _EOF_ >> ts-jest.config.json
{
  "preset": "ts-jest",
  "testEnvironment": "node",
  "roots": ["<rootDir>/test"],
  "setupFiles": ["dotenv/config"]
}
_EOF_


  mkdir test
  touch test/index.test.ts
  cat << _EOF_ >> test/index.test.ts
describe('index', () => {
  it('should pass', () => {
    expect(true).toBe(true);
  });
});
_EOF_

  npx tsc --init --target ES2022 --outDir './dist' 
  # we can't pipe from one file to itself, so we use that chance to build the tsconfig.test.json
  cat tsconfig.json | perl -pe 's/(\/\*.*\*\/)//;s/\/\/.*$//' | jq '.include = ["src","test"] | .compilerOptions.strict = true | .compilerOptions.sourceMap = true' > tsconfig.test.json
  cp tsconfig.test.json tsconfig.json
  echo '{ "extends": "./tsconfig.json" }' > tsconfig.test.json

  mkdir src
  touch src/env.ts
  touch src/index.ts
  cat << _EOF_ >> src/env.ts
import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('production')
});

export const env = envSchema.parse(process.env);
_EOF_

  cat << _EOF_ >> src/index.ts
import { env } from './env'; 
import { setTimeout as wait } from 'timers/promises';

async function main(): Promise<void> {
  await wait(100);

  console.log('Hello, World!', { env });
};

main()
  .then(() => {
    console.log('Done!')
  })
  .catch((error: unknown) => {
    console.error('Error:', error);
  });
_EOF_

  echo "import '@total-typescript/ts-reset';" > reset.d.ts

  npm pkg set version="0.1.0"
  npm pkg set main="dist/src/index.js"
  npm pkg set scripts.build="rimraf ./dist && tsc -p tsconfig.json"
  npm pkg set scripts.build:test:js="rimraf ./dist && tsc -p tsconfig.test.json"
  npm pkg set scripts.test:js="npm run build:test:js && jest --config jest.config.json"
  npm pkg set scripts.test:ts="jest --config ts-jest.config.json"
  npm pkg set scripts.test="npm run test:ts"
  npm pkg set scripts.start="node -r dotenv/config ./dist/src/index.js"
  npm pkg set scripts.dev="ts-node -r dotenv/config ./src/index.ts"
  npm pkg set scripts.dev:debug="node --inspect-brk -r ts-node/register -r dotenv/config ./src/index.ts" 
  npm pkg set scripts.pretty="prettier --write 'src/**/*.ts'"
  npm pkg set scripts.pretty:check="prettier --check 'src/**/*.ts'"
  npm pkg set scripts.lint="eslint"

  npx husky init

  echo "npm run pretty:check && npm run lint" > .husky/pre-commit
  echo 'npx --no -- commitlint --edit $1'     > .husky/commit-msg
  echo ""                                     > .husky/pre-push  

  cat << _EOF_ >> .husky/pre-push
STATUS=\$(git status --porcelain | wc -l | xargs)
FILES=\$(git status --porcelain | sed -n "s;^.. \(.*\)\$;\\\\\t\\\\\t\1\\\\\n;p")

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

if [ \$STATUS -ne 0 ]; then
  echo \$RED'✖ Make sure all changes are staged and committed before pushing'\$NO_COLOR
  echo \$RED'\tDetected changes in:'\$NO_COLOR
  echo \$RED\$FILES\$NO_COLOR
  exit 1
fi

echo \$GREEN'✓ No changes left to commit'\$NO_COLOR

_EOF_

  npx prettier --write './**/*.{js,json,ts}'

  git add --all
  git commit -am "chore: initial commit"

  npm run dev
  npm run test:ts

  npm run build
  npm run start
  npm run test:js
}

cbp(){
  if [ -z "$1" ]
    then
      echo "Project name not provided"
      return 1
  fi

  mkdir $1
  cd $1
  git init

  echo "node_modules\n.DS_Store\n.env*\ndist" > .gitignore
  touch .env

  bun init --yes
  rm *.ts
  cat << _EOF_ >> bunfig.toml
[install]
exact = true
_EOF_

  bun add -D rimraf typescript eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin prettier @commitlint/cli @commitlint/config-conventional husky @total-typescript/ts-reset jest @types/jest ts-jest @types/bun
  bun add zod

  cat << _EOF_ >> eslint.config.js
import typescriptParser from '@typescript-eslint/parser';
import tsEslintPlugin from '@typescript-eslint/eslint-plugin';

export default [
  tsEslintPlugin.configs['recommended-type-checked'],
  {
    languageOptions: { parser: typescriptParser, parserOptions: { project: './tsconfig.json' } },
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    ignores: ['reset.d.ts'],
    rules: {
      'consistent-return': 1,
      eqeqeq: 1,
      'no-param-reassign': 1,
      '@typescript-eslint/no-floating-promises': 2,
      '@typescript-eslint/explicit-function-return-type': 2,
      '@typescript-eslint/explicit-module-boundary-types': 2
    }
  }
];
_EOF_
  echo '{ "printWidth": 120, "tabWidth": 2, "useTabs": false, "semi": true, "singleQuote": true, "trailingComma": "none", "arrowParens": "avoid" }' > .prettierrc.json
  echo '{ "extends": ["@commitlint/config-conventional"] }' > .commitlintrc.json

  cat << _EOF_ >> ts-jest.config.json
{
  "preset": "ts-jest",
  "testEnvironment": "node",
  "roots": ["<rootDir>/test"],
}
_EOF_


  mkdir test
  touch test/index.test.ts
  cat << _EOF_ >> test/index.test.ts
describe('index', () => {
  it('should pass', () => {
    expect(true).toBe(true);
  });
});
_EOF_

  cat tsconfig.json | perl -pe 's/(\/\*.*\*\/)//;s/\/\/.*$//' | jq '.include = ["src","test"] | .compilerOptions.esModuleInterop = true' > tsconfig.test.json
  cp tsconfig.test.json tsconfig.json
  echo '{ "extends": "./tsconfig.json" }' > tsconfig.test.json

  mkdir src
  touch src/env.ts
  touch src/index.ts
  cat << _EOF_ >> src/env.ts
import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('production')
});

export const env = envSchema.parse(process.env);
_EOF_

  cat << _EOF_ >> src/index.ts
import { env } from './env'; 
import { setTimeout as wait } from 'timers/promises';

async function main(): Promise<void> {
  await wait(100);

  console.log('Hello, World!', { env });
};

main()
  .then(() => {
    console.log('Done!')
  })
  .catch((error: unknown) => {
    console.error('Error:', error);
  });
_EOF_

  echo "import '@total-typescript/ts-reset';" > reset.d.ts

  npm pkg set version="0.1.0"
  npm pkg set main="./src/index.ts"
  npm pkg set scripts.test="jest --config ts-jest.config.json"
  npm pkg set scripts.start="bun ./src/index.ts"
  npm pkg set scripts.pretty="prettier --write 'src/**/*.ts'"
  npm pkg set scripts.pretty:check="prettier --check 'src/**/*.ts'"
  npm pkg set scripts.lint="eslint"

  bunx husky init

  echo "bun run pretty:check && bun run lint" > .husky/pre-commit
  echo 'bunx --no -- commitlint --edit $1'     > .husky/commit-msg
  echo ""                                     > .husky/pre-push  

  cat << _EOF_ >> .husky/pre-push
STATUS=\$(git status --porcelain | wc -l | xargs)
FILES=\$(git status --porcelain | sed -n "s;^.. \(.*\)\$;\\\\\t\\\\\t\1\\\\\n;p")

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

if [ \$STATUS -ne 0 ]; then
  echo \$RED'✖ Make sure all changes are staged and committed before pushing'\$NO_COLOR
  echo \$RED'\tDetected changes in:'\$NO_COLOR
  echo \$RED\$FILES\$NO_COLOR
  exit 1
fi

echo \$GREEN'✓ No changes left to commit'\$NO_COLOR

_EOF_

  bunx prettier --write './**/*.{js,json,ts}'

  git add --all
  git commit -am "chore: initial commit"

  bun run start
  bun run test
}

md2pdf(){
  npx --yes markdown-pdf $1
}

dsf(){
  diff -u $1 $2 | diff-so-fancy
}

fni(){
  NODE_VERSION=$1
  echo "Getting global packages"
  GLOBAL_PACKAGES=$(npm ls -g --json | jq '.dependencies | keys | .[]' | xargs)

  fnm install $NODE_VERSION
  fnm use $NODE_VERSION

  echo "Reinstalling global packages"
  echo $GLOBAL_PACKAGES | xargs npm i -g
}

_npm_run_completion() {
  if [[ ! -f package.json ]]; then
    return 0
  fi

  if ! command -v jq &> /dev/null; then
    return 0
  fi

  if ! jq -e '.scripts' package.json &> /dev/null; then
    return 0
  fi

  local -a script_names
  script_names=($(jq -r '.scripts | keys[]' package.json))

  _describe 'script' script_names
}

compdef _npm_run_completion "npm run" "yarn" "yarn run" 
