local dap = require("dap")
dap.adapters.node2 = {
	type = "executable",
	command = "node",
	args = { os.getenv("HOME") .. "/repos/javascript/vscode-node-debug2/out/src/nodeDebug.js" },
}

-- require('dap').set_log_level('INFO')
dap.defaults.fallback.terminal_win_cmd = "20split new"
vim.fn.sign_define("DapBreakpoint", { text = "⏹", texthl = "", linehl = "", numhl = "" })
vim.fn.sign_define("DapBreakpointRejected", { text = "↩️", texthl = "", linehl = "", numhl = "" })
vim.fn.sign_define("DapStopped", { text = "▶️", texthl = "", linehl = "", numhl = "" })

vim.keymap.set("n", "<leader>dh", function()
	require("dap").toggle_breakpoint()
end)
vim.keymap.set("n", "<leader>dH", ":lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>")
vim.keymap.set("n", "<A-k>", function()
	require("dap").step_out()
end)
vim.keymap.set("n", "<A-l>", function()
	require("dap").step_into()
end)
vim.keymap.set("n", "<A-j>", function()
	require("dap").step_over()
end)
vim.keymap.set("n", "<leader>dc", function()
	require("dap").continue()
end)
vim.keymap.set("n", "<leader>dn", function()
	require("dap").run_to_cursor()
end)
vim.keymap.set("n", "<leader>dt", function()
	require("dap").terminate()
end)
vim.keymap.set("n", "<leader>dR", function()
	require("dap").clear_breakpoints()
end)
vim.keymap.set("n", "<leader>de", function()
	require("dap").set_exception_breakpoints({ "all" })
end)
vim.keymap.set("n", "<leader>da", function()
	require("debugHelper").attach()
end)
vim.keymap.set("n", "<leader>di", function()
	require("dap.ui.widgets").hover()
end)
vim.keymap.set("n", "<leader>d?", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.scopes)
end)
vim.keymap.set("n", "<leader>dk", ':lua require"dap".up()<CR>zz')
vim.keymap.set("n", "<leader>dj", ':lua require"dap".down()<CR>zz')
vim.keymap.set("n", "<leader>dr", ':lua require"dap".repl.toggle({}, "vsplit")<CR><C-w>l')

-- nvim-telescope/telescope-dap.nvim
require("telescope").load_extension("dap")
vim.keymap.set("n", "<leader>ds", ":Telescope dap frames<CR>")
-- vim.keymap.set('n', '<leader>dc', ':Telescope dap commands<CR>')
vim.keymap.set("n", "<leader>db", ":Telescope dap list_breakpoints<CR>")

require("nvim-dap-virtual-text").setup()
vim.g.dap_virtual_text = true

-- David-Kunz/jester
-- require'jester'.setup({ path_to_jest = "/usr/local/bin/jest" })
vim.keymap.set("n", "<leader>tt", function()
	require("jester").run()
end)
vim.keymap.set("n", "<leader>t_", function()
	require("jester").run_last()
end)
vim.keymap.set("n", "<leader>tf", function()
	require("jester").run_file()
end)
vim.keymap.set("n", "<leader>d_", function()
	require("jester").debug_last()
end)
vim.keymap.set("n", "<leader>df", function()
	require("jester").debug_file()
end)
vim.keymap.set("n", "<leader>dq", function()
	require("jester").terminate()
end)
vim.keymap.set("n", "<leader>dd", function()
	require("jester").debug()
end)
