local mark = require('harpoon.mark')
local ui = require('harpoon.ui')

vim.keymap.set('n', '<leader>ha', mark.add_file, { desc = '[harpoon] add file' })
vim.keymap.set('n', '<leader>hf', ui.toggle_quick_menu, { desc = '[harpoon] show files' })

vim.keymap.set('n', '<leader>h1', function()
	ui.nav_file(1)
end, { desc = '[harpoon] bookmark file' })
vim.keymap.set('n', '<leader>h2', function()
	ui.nav_file(2)
end, { desc = '[harpoon] bookmark file' })
vim.keymap.set('n', '<leader>h3', function()
	ui.nav_file(3)
end, { desc = '[harpoon] bookmark file' })
vim.keymap.set('n', '<leader>h4', function()
	ui.nav_file(4)
end, { desc = '[harpoon] bookmark file' })
